services:
  wallet1:
    build:
      context: .
      dockerfile: Dockerfile
    image: wallet1:latest
    container_name: wallet1
    ports:
      - "8001:8001"
    environment:
      - PORT=${PORT1}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_SSLMODE=${DB_SSLMODE}
      - DB_MAX_OPEN_CONNS=${DB_MAX_OPEN_CONNS}
      - DB_MAX_IDLE_CONNS=${DB_MAX_IDLE_CONNS}
      - DB_CONN_MAX_LIFETIME=${DB_CONN_MAX_LIFETIME}
    volumes:
      - ./app:/app
    depends_on:
      - postrgres_wallet
      
  
  wallet2:
    build:
      context: .
      dockerfile: Dockerfile
    image: wallet2:latest
    container_name: wallet2
    ports:
      - "8002:8002"
    environment:
      - PORT=${PORT2}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_SSLMODE=${DB_SSLMODE}
      - DB_MAX_OPEN_CONNS=${DB_MAX_OPEN_CONNS}
      - DB_MAX_IDLE_CONNS=${DB_MAX_IDLE_CONNS}
      - DB_CONN_MAX_LIFETIME=${DB_CONN_MAX_LIFETIME}
    volumes:
      - ./app:/app
    depends_on:
      - postrgres_wallet

  postrgres_wallet:
    image: postgres:latest
    container_name: ${DB_HOST}
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data_wallet:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: wallet_nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - wallet1
      - wallet2

volumes:
  postgres_data_wallet:
